project:
  type: website

website:
  title: "William Tyler Bradley"
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  site-url: https://www.williamtylerbradley.com
  description: "Website for W T Bradley"
  navbar:
    title: "William Tyler Bradley"
    background: primary
    left:
      - text: "Posts"
        file: index.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        aria-label: github
        href: https://github.com/WilliamTylerBradley
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/williamtylerbradley/
  page-footer:
    center:
      - text: "Copyright 2026, William Tyler Bradley"
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light:
        - default
        - calathea.scss
      dark:
        - default
        - calathea_dark.scss
    css: styles.css
    highlight-style: calathea.theme
    code-copy: true

editor: source