project:
  type: website

website:
  favicon: favicon.png
  navbar:
    background: "#1E271A"
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        aria-label: github
        href: https://github.com/WilliamTylerBradley
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/williamtylerbradley/
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/w_tyler_bradley
  page-footer: 
    center: "Copyright 2022, William Tyler Bradley"
    background: "#263121"
format:
  html:
    theme: default
    css: styles.css
    highlight-style: calathea.theme
    code-copy: true

editor: source